//
// Created by Maikel Nadolski on 06.06.18.
//

#ifndef REACTIVEEULERSOLVER_SEGMENTED_RESOURCE_HPP
#define REACTIVEEULERSOLVER_SEGMENTED_RESOURCE_HPP

#endif //REACTIVEEULERSOLVER_SEGMENTED_RESOURCE_HPP
